=== GirocheckFinancial/girocheck2/VTReporting/src/main/resources/TransactionFK.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xsd:complexType name="TransactionType">
		<xsd:sequence>
			<xsd:element type="xsd:decimal" name="id"/>
			<xsd:element type="xsd:decimal" name="idMerchant" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:decimal" name="idTerminal" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:decimal" name="idClient" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="operation" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="requestId" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="maskCardNumber" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="payoutAmount" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="feeAmount" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="amount" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="dateTime" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="type" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="checkNumber" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="makerName" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="resultMessage" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="resultCode" nillable="true" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="Report">
		<xsd:complexType>
			<xsd:sequence>
			    <xsd:element name="General" type="GeneralType" maxOccurs="unbounded"/>
				<xsd:element name="Transaction" type="TransactionType" maxOccurs="unbounded"/>
				<xsd:element name="Merchant" type="MerchantType" maxOccurs="unbounded"/>
				<xsd:element name="Terminal" type="TerminalType" maxOccurs="unbounded"/>
				<xsd:element name="Client" type="ClientType" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>

		<xsd:key name="PK_transaction_id">
			<xsd:selector xpath=".//Transaction"/>
			<xsd:field xpath="id"/>
		</xsd:key>

		<xsd:key name="PK_merchant_id">
			<xsd:selector xpath=".//Merchant"/>
			<xsd:field xpath="id"/>
		</xsd:key>

		<xsd:key name="PK_terminal_id">
			<xsd:selector xpath=".//Terminal"/>
			<xsd:field xpath="id"/>
		</xsd:key>

		<xsd:key name="PK_client_id">
			<xsd:selector xpath=".//Client"/>
			<xsd:field xpath="id"/>
		</xsd:key>

		<xsd:keyref name="FK_merchant_transaction" refer="PK_merchant_id">
			<xsd:selector xpath=".//Transaction"/>
			<xsd:field xpath="idMerchant"/>
		</xsd:keyref>

		<xsd:keyref name="FK_terminal_transaction" refer="PK_terminal_id">
			<xsd:selector xpath=".//Transaction"/>
			<xsd:field xpath="idTerminal"/>
		</xsd:keyref>

		<xsd:keyref name="FK_client_transaction" refer="PK_client_id">
			<xsd:selector xpath=".//Transaction"/>
			<xsd:field xpath="idClient"/>
		</xsd:keyref>

	</xsd:element>

	<xsd:complexType name="MerchantType">
		<xsd:sequence>
			<xsd:element type="xsd:decimal" name="id"/>
			<xsd:element type="xsd:string" name="legalName" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="description" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="sic" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="address" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="zipcode" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="state" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="city" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="phone" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="idPosOrderExp" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="idTellerOrderExp" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="oEAgentNumber" nillable="true" minOccurs="0"/>
                        <xsd:element type="xsd:string" name="customerName" nillable="true" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="TerminalType">
		<xsd:sequence>
			<xsd:element type="xsd:decimal" name="id"/>
			<xsd:element type="xsd:string" name="serialNumber" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="description" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="merchantName" nillable="true" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ClientType" >
		<xsd:sequence>
			<xsd:element type="xsd:decimal" name="id"/>
			<xsd:element type="xsd:string" name="first" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="last" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="phone" nillable="true" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="GeneralType" >
		<xsd:sequence>
			<xsd:element type="xsd:string" name="header" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="footer" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="fromDate" nillable="true" minOccurs="0"/>
			<xsd:element type="xsd:string" name="toDate" nillable="true" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== GirocheckFinancial/girocheck2/VTReporting/src/main/resources/TransactionFK.xml
<?xml version="1.0"?>
<Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TransactionFK.xsd">
        <General>
                <header>asd</header>
                <footer>dede</footer>
                <fromDate>20150910</fromDate>
                <toDate>20150910</toDate>
        </General>	
        <Transaction>
                <id>11</id>
		<idMerchant>1</idMerchant>
		<idTerminal>2</idTerminal>
		<idClient>3</idClient>
		<operation>01</operation>
		<requestId>12345</requestId>
		<maskCardNumber>1234567890987654</maskCardNumber>
		<payoutAmount>100</payoutAmount>
		<feeAmount>3</feeAmount>
		<amount>103</amount>
		<dateTime>20150910</dateTime>
		<type>R</type>
		<checkNumber>321321321</checkNumber>
		<makerName>adasdasd</makerName>
		<resultMessage>This is Test Data. No data available.</resultMessage>
                <resultCode>0</resultCode>
	</Transaction>
	<Merchant>
		<id>1</id>
		<legalName>lolo</legalName>
		<description>qaqweqwe</description>
		<sic>111</sic>
		<address>adasdasd</address>
                <zipcode>12345</zipcode>
                <state>as</state>
                <city>asdasdasd</city>
                <phone>123123123123</phone>
                <idPosOrderExp>1231231231</idPosOrderExp>
                <idTellerOrderExp>111333</idTellerOrderExp>
                <oEAgentNumber>123123123</oEAgentNumber>
                <customerName>asdasd</customerName>
	</Merchant>
	<Terminal>
		<id>2</id>
                <serialNumber>1234567889</serialNumber>
                <description>aaaaaa</description>
                <merchantName>asdasd</merchantName>
	</Terminal>
	<Client>
		<id>3</id>
                <first>qwqw</first>
                <last>asas</last>
                <phone>123456789</phone>
	</Client>
</Report>
